USE [master]
GO

/****** Object:  Database [CafeSmart]    Script Date: 26/11/2024 12:49:18 p. m. ******/
CREATE DATABASE [CafeSmart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CafeSmart', FILENAME = N'C:\SQLData\CafeSmart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CafeSmart_log', FILENAME = N'C:\SQLData\CafeSmart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CafeSmart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CafeSmart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CafeSmart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CafeSmart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CafeSmart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CafeSmart] SET ARITHABORT OFF 
GO

ALTER DATABASE [CafeSmart] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CafeSmart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CafeSmart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CafeSmart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CafeSmart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CafeSmart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CafeSmart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CafeSmart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CafeSmart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CafeSmart] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CafeSmart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CafeSmart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CafeSmart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CafeSmart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CafeSmart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CafeSmart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CafeSmart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CafeSmart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CafeSmart] SET  MULTI_USER 
GO

ALTER DATABASE [CafeSmart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CafeSmart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CafeSmart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CafeSmart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CafeSmart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CafeSmart] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CafeSmart] SET QUERY_STORE = ON
GO

ALTER DATABASE [CafeSmart] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CafeSmart] SET  READ_WRITE 
GO


